### ISSUE TITLE
A project status can't be updated anymore

### ISSUE THREAD

**Issue by djaiss** [officelifehq/officelife#774] opened 2021-04-15 03:44 UTC
Since vue 3 upgrade.

**Comment by asbiin** [comment] 2021-04-15 06:43
This is working, but the author of the update must be part of the project.
We should either handle the error best, or make the "Update status" button only available for members.

**Comment by asbiin** [comment] 2021-07-04 12:16
This is a duplicate of #995

**Closed by asbiin** 2021-07-04 12:16 UTC
Labels: bug
